### ISSUE TITLE
How to write template of chiral alchol to ketone.

### ISSUE THREAD

**Issue by shomjm** [connorcoley/rdchiral#44]
I want to write template of chiral alchol to ketone.
In the case of not chiral alchol,
template `"[Oh:1][C:2]([C:3])[C:4]>>[O:1]=[C:2]([C:3])[C:4]"` worked well for reactant `"OC(C)CC"`: then it gave `['CCC(C)=O']`.
But in the case of chiral alchol,
template `"[Oh:1][C@H:2]([C:3])[C:4]>>[O:1]=[C:2]([C:3])[C:4]"` didn't work for reactant `"O[C@H](C)CC"`: then it gave `[]`.
How I write template for chiral alchol?

**Comment by connorcoley** [comment]
This is because your chiral template specifies that the carbon with atom map 2 has a hydrogen in the reactants side and, when copied over to the product, is left implicit. This leads to a valence issue, which you can see if you install rdchiral from source with `python setup.py install` and set `PLEVEL = 99` in the header of `utils.py`:

```[O:1]=[CH:2]([CH3:3])[CH2:4][CH3:5], Explicit valence for atom # 1 C, 5, is greater than permitted```

You can fix this by correcting your chiral template to the following:

```"[OH:1][C@H:2]([C:3])[C:4]>>[O:1]=[CH0:2]([C:3])[C:4]"```

**Comment by shomjm** [comment]
Thank you for your reply.
Your template include "CH0" worked well!
